main:
  - identifier: "home"
    name: "home"
    weight: 100
    url: "/"
  - identifier: "blog"
    name: "blog"
    weight: 130
    url: "/blog/"
  - identifier: "contact"
    name: "contact"
    weight: 1000
    url: "/contact/"

footer:
  - identifier: "MPL-2.0"
    name: "MPL-2.0"
    weight: 1
    url: "http://mozilla.org/MPL/2.0/"
